FROM python:3.6.4

# instal environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends netcat \
    && apt-get -q clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install dependencies
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# run server
CMD ["./entrypoint.sh"]